name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  owner:
    description: 'Owner name'
    required: true
  repo:
    description: 'Repo name'
    required: true 
  pr_number:
    description: 'PR number'
    required: true
  token:
    description: 'Your GitHub token'
    required: true
  project_path:
    description: 'Project path'
    required: true   

# Define your outputs here.
outputs:
  comment_content:
    description: 'GitHub PR comment content'

runs:
  using: node20
  main: dist/index.js