name: Publish npm packages

on:
  # manually triggering the workflow if desired
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  publish-npm-packages:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup npmrc
        run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}\ngit-checks=false" > .npmrc
      
      - name: Disable Gitchecks
        run: echo "git-checks=false" > .npmrn

      - name: install dependencies
        run: pnpm install

      - name: Install Doppler CLI for env variables
        uses: dopplerhq/cli-action@v2

      - run: doppler run -- pnpm build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - run: doppler run -- pnpm test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}