name: Sync Examples

on:
  push:
    # Trigger if an example CHANGELOG is changed on main -> usually after a release
    branches:
      - "main"
    paths:
      - "**/example/CHANGELOG.md"
      - "**/examples/*/CHANGELOG.md"
  # TODO REMOVE - ONLY FOR TESTING
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

#
# The jobs should do a few things:
# 1. Check out the repository
# 2. Set up pnpm
# 3. Run `pnpm pack` in the /inlang/source-code/paraglide/paraglide-js/example directory
# 4. Unpack the generated tarball 
# 5. Commit the unpacked tarball to https://github.com/lorissigrist/paraglide-js-example
# 6. Force Push the commit to the repository

jobs:
  sync-examples:
    strategy:
      matrix:
        include:

          - path: inlang/source-code/paraglide/paraglide-js-adapter-sveltekit/example
            repo: "LorisSigrist/paraglide-sveltekit-example"
            token: ${{ secrets.EXAMPLE_REPOS_ACCESS_TOKEN }}
            token_user: "LorisSigrist"

          - path: inlang/source-code/paraglide/paraglide-js-adapter-astro/example
            repo: "LorisSigrist/paraglide-astro-example"
            token: ${{ secrets.EXAMPLE_REPOS_ACCESS_TOKEN }}
            token_user: "LorisSigrist"
          
        path:
          - inlang/source-code/paraglide/paraglide-js-adapter-sveltekit/example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      # Unfortunately this is necessary
      - name: Install Dependencies
        run: pnpm install

      - name: Pack & Unpack
        run: | 
          cd ${{ matrix.path }} &&
          pnpm pack --pack-destination ./tmp &&
          tar -xvf ./tmp/*.tgz

      - name: Push Package Folder
        run: |
          cd ${{ matrix.path }}/package
          git init -b main
          git config user.name "sync-examples-action"
          git config user.email "noreply@opral.com"
          git add -A . 
          git commit -m "chore: sync with opral/monorepo"
          git status
          git remote add origin "https://${{ matrix.token_user }}:${{ matrix.token }}@github.com/${{ matrix.repo }}.git"
          git push --force origin main