name: Test GitHub Actions Lint

on:
  pull_request:
    branches:
      - main

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
  
jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Read JSON file
        id: read-json
        run: |
          json_file_path="./project.inlang/settings.json"
          json_content=$(cat "$json_file_path")
          echo "::set-output name=json_content::$json_content"

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Node.js script
        run: |
          // Example Node.js script to import modules
          const fs = require('fs');
          const path = require('path');
          
          // Accessing the JSON content passed from previous step
          const jsonContent = JSON.parse(process.env.json_content);
          
          // Example of using the JSON content
          console.log('JSON content:', jsonContent);
          
          // Example of importing all Node.js modules within a specific path
          const modulePath = './project.inlang';
          const modules = jsonContent.modules.map(module => require(path.join(modulePath, module)));
          
          console.log('Imported modules:', modules);

      - name: Install Dependencies
        run: pnpm install

      - name: Install Doppler CLI for env variables
        uses: dopplerhq/cli-action@v2

      - name: Build
        run: doppler run -- pnpm --filter @inlang/github-lint-action... build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - name: Test Local Action
        id: test-action
        uses: ./inlang/source-code/github-lint-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.comment_content }}"